name: ${project.name}
version: ${project.version}
description: ${project.description}
author: Whitescan
api-version: 1.18
main: me.whitescan.antifalldamage.AntiFalldamage

commands:
  antifalldamage:
    description: Toggle antifalldamage for a player
    permission: antifalldamage.use
    usage: </command>