name: ${project.name}
version: ${project.version}
description: ${project.description}
main: me.whitescan.antifalldamage.AntiFalldamage
author: Whitescan
api-version: 1.16
description: A simple falldamage protection

commands:
  antifalldamage:
    description: Admit to a rulebreaking
    permission: antifalldamage.use
    usage: </command>